name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_USERNAME: ${{ secrets.USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.PASSWORD }}
          CYPRESS_LOCKED_USERNAME: ${{ secrets.LOCKED_USERNAME }}
